#!/usr/bin/python

import sys
from optparse import OptionParser
sys.path.append("/opt/toas/cloudmanagementtools/tools/lib")
from toascommon import *

def main():
	parser = OptionParser()
	parser.add_option("-i","--instance",action="store", dest="instance", help="Number of the TOAS instance", type="int")
	parser.add_option("-k","--keyfile",action="store",dest="keyfile",help="Optional file to store the instance key")

	(options, args) = parser.parse_args()
	if(options.instance == None):
		parser.error("No instance given")
	try:
		instance = getInstance(options.instance)
		if(instance == None):
			print "Instance "+options.instance+" not found"
			sys.exit()
		
		print "Instance %s (%d):" % (instance.name,instance.id)
		clusters = getInstanceClusters(instance.id)
		for c in clusters:
			machines = getClusterMachines(con, c.id)
			print "Service %s (cluster id %d) " % (c.name, c.id)
			for m in machines:
				print "-- Machine %d (%s) %s %s" % (m.id,m.instanceId,m.type,m.dnsName)
		
		key = getInstanceKey(instance.id)
		if(options.keyfile != None):
			fo = open(options.keyfile, "w")
			fo.write(key.secretKey)
			fo.close()

	except mdb.Error, e:
		print "Error %d: %s" % (e.args[0], e.args[1])
		sys.exit(1);

	finally:
		if con:
			con.close()

if __name__ == '__main__':
	main()

