#!/bin/sh

OPENINFINITY_DIR=/opt/openinfinity/3.0.0
INCLUDE_DIRS_FILE=$OPENINFINITY_DIR/backup/include-dirs.d/mariadb
BACKUP_TMP_DIR=$OPENINFINITY_DIR/backup/tmp

# Make database dump
$OPENINFINITY_DIR/mariadb/bin/mysqldump -ubackup -ptoasbackup --all-databases --lock-all-tables | gzip > $BACKUP_TMP_DIR/mariadb-all-databases-dump.gz || exit 1

echo $BACKUP_TMP_DIR > $INCLUDE_DIRS_FILE || exit 1

