#!/bin/sh

OPENINFINITY_DIR=/opt/openinfinity/3.0.0
BACKUP_TMP_DIR=$OPENINFINITY_DIR/backup/tmp

# Restore databases from the dump
gunzip $BACKUP_TMP_DIR/mariadb-all-databases-dump.gz | $OPENINFINITY_DIR/mariadb/bin/mysql -ubackup -ptoasbackup --silent || exit 1

rm -f $BACKUP_TMP_DIR/mariadb-all-databases-dump.gz

