#!/bin/sh

# In case of MongoDB, the following procedure is followed:
# http://docs.mongodb.org/manual/tutorial/restore-sharded-cluster/

source /opt/openinfinity/3.0.0/backup/common/bigdata-common

if [ "x$BIGDATA_ROLE" = "x" ] ; then
    echo "Can't prepare cluster restore because this node is not part of a bigdata/nosql cluster" >/dev/stderr
    exit 1
elif [ "$BIGDATA_ROLE" = "config" ] ; then
    # --------------------------------------------------------------------------
    # 1. Stop all mongod and mongos processes.
    # --------------------------------------------------------------------------
    /etc/init.d/mongos stop || exit 1
    /etc/init.d/mongo-cfgsrv stop || exit 1 # also config servers have to be stopped
elif [ "$BIGDATA_ROLE" = "shard" ] ; then
    # --------------------------------------------------------------------------
    # 1. Stop all mongod and mongos processes.
    # --------------------------------------------------------------------------
    /etc/init.d/mongod start || exit 1
else
    # TODO: Hadoop support?
    echo "At moment other than MongoDB bigdata restores are not supported." >/dev/stderr
    exit 1
fi

